language: objective-c
osx_image: xcode7.3
xcode_workspace: welcome-ios-swift.xcworkspace
xcode_scheme: welcome-ios-swift
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master